// Mocks generated by Mockito 5.4.6 from annotations
// in riverpod_keyboard/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:riverpod_keyboard/models/keyboard_play.dart' as _i2;
import 'package:riverpod_keyboard/services/keyboard_play_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeKeyboardPlay_0 extends _i1.SmartFake implements _i2.KeyboardPlay {
  _FakeKeyboardPlay_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [KeyboardPlayService].
///
/// See the documentation for Mockito's code generation for more information.
class MockKeyboardPlayService extends _i1.Mock
    implements _i3.KeyboardPlayService {
  MockKeyboardPlayService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> playNote(int? note) => (super.noSuchMethod(
        Invocation.method(
          #playNote,
          [note],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.KeyboardPlay> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<_i2.KeyboardPlay>.value(_FakeKeyboardPlay_0(
          this,
          Invocation.method(
            #initialize,
            [],
          ),
        )),
      ) as _i4.Future<_i2.KeyboardPlay>);

  @override
  _i4.Future<void> playPhrase(
    List<int>? notes,
    int? interval,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #playPhrase,
          [
            notes,
            interval,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
